config/routes.rb
Rails.application.routes.draw do
  resources :social_media_investigations
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root 'social_media_investigations#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/social_media_investigation.rb
class SocialMediaInvestigation < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/social_media_investigations_controller.rb
class SocialMediaInvestigationsController < ApplicationController
  before_action :set_social_media_investigation, only: %i[ show edit update destroy ]

  # GET /social_media_investigations or /social_media_investigations.json
  def index
    @social_media_investigations = SocialMediaInvestigation.all
  end

  # GET /social_media_investigations/1 or /social_media_investigations/1.json
  def show
  end

  # GET /social_media_investigations/new
  def new
    @social_media_investigation = SocialMediaInvestigation.new
  end

  # GET /social_media_investigations/1/edit
  def edit
  end

  # POST /social_media_investigations or /social_media_investigations.json
  def create
    @social_media_investigation = SocialMediaInvestigation.new(social_media_investigation_params)

    respond_to do |format|
      if @social_media_investigation.save
        format.html { redirect_to @social_media_investigation, notice: "Social media investigation was successfully created." }
        format.json { render :show, status: :created, location: @social_media_investigation }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @social_media_investigation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /social_media_investigations/1 or /social_media_investigations/1.json
  def update
    respond_to do |format|
      if @social_media_investigation.update(social_media_investigation_params)
        format.html { redirect_to @social_media_investigation, notice: "Social media investigation was successfully updated." }
        format.json { render :show, status: :ok, location: @social_media_investigation }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @social_media_investigation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /social_media_investigations/1 or /social_media_investigations/1.json
  def destroy
    @social_media_investigation.destroy!

    respond_to do |format|
      format.html { redirect_to social_media_investigations_path, status: :see_other, notice: "Social media investigation was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_social_media_investigation
      @social_media_investigation = SocialMediaInvestigation.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def social_media_investigation_params
      params.require(:social_media_investigation).permit(:platform, :platform_account_key, :started_at, :ended_at, :api_payload)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/social_media_investigations_helper.rb
module SocialMediaInvestigationsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Social Media Checker" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/social_media_investigations/_form.html.erb
<%= form_with(model: social_media_investigation) do |form| %>
  <% if social_media_investigation.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(social_media_investigation.errors.count, "error") %> prohibited this social_media_investigation from being saved:</h2>

      <ul>
        <% social_media_investigation.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :platform, style: "display: block" %>
    <%= form.number_field :platform %>
  </div>

  <div>
    <%= form.label :platform_account_key, style: "display: block" %>
    <%= form.text_field :platform_account_key %>
  </div>

  <div>
    <%= form.label :started_at, style: "display: block" %>
    <%= form.datetime_field :started_at %>
  </div>

  <div>
    <%= form.label :ended_at, style: "display: block" %>
    <%= form.datetime_field :ended_at %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/social_media_investigations/_social_media_investigation.html.erb
<div id="<%= dom_id social_media_investigation %>">
  <p>
    <strong>Platform:</strong>
    <%= social_media_investigation.platform %>
  </p>

  <p>
    <strong>Platform account key:</strong>
    <%= social_media_investigation.platform_account_key %>
  </p>

  <p>
    <strong>Started at:</strong>
    <%= social_media_investigation.started_at %>
  </p>

  <p>
    <strong>Ended at:</strong>
    <%= social_media_investigation.ended_at %>
  </p>

  <p>
    <strong>Api payload:</strong>
    <%= social_media_investigation.api_payload %>
  </p>

</div>

app/views/social_media_investigations/edit.html.erb
<% content_for :title, "Editing social media investigation" %>

<h1>Editing social media investigation</h1>

<%= render "form", social_media_investigation: @social_media_investigation %>

<br>

<div>
  <%= link_to "Show this social media investigation", @social_media_investigation %> |
  <%= link_to "Back to social media investigations", social_media_investigations_path %>
</div>

app/views/social_media_investigations/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Social media investigations" %>

<h1>Social media investigations</h1>

<div id="social_media_investigations">
  <% @social_media_investigations.each do |social_media_investigation| %>
    <%= render social_media_investigation %>
    <p>
      <%= link_to "Show this social media investigation", social_media_investigation %>
    </p>
  <% end %>
</div>

<%= link_to "New social media investigation", new_social_media_investigation_path %>

app/views/social_media_investigations/new.html.erb
<% content_for :title, "New social media investigation" %>

<h1>New social media investigation</h1>

<%= render "form", social_media_investigation: @social_media_investigation %>

<br>

<div>
  <%= link_to "Back to social media investigations", social_media_investigations_path %>
</div>

app/views/social_media_investigations/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @social_media_investigation %>

<div>
  <%= link_to "Edit this social media investigation", edit_social_media_investigation_path(@social_media_investigation) %> |
  <%= link_to "Back to social media investigations", social_media_investigations_path %>

  <%= button_to "Destroy this social media investigation", @social_media_investigation, method: :delete %>
</div>